name: Remove Draft PR

on:
  pull_request:
    types: [labeled]  # Запускается при добавлении метки

jobs:
  remove-draft:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'test'  # Проверяем, что добавлена именно метка "test"
    steps:
      - name: Remove Draft using GitHub API
        run: |
          curl -X PATCH \
               -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
               -d '{"draft": false}'

